### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by iBreakEverything** [Citrinate/CS2Interface#4] opened 2024-02-12 21:23 UTC
I added the plugin and it crashed, then i removed all the plugins but your and it still crashed.
Here is the log. 

```
2024-02-12 23:13:27|ArchiSteamFarm-12345|INFO|ASF|InitCore() ArchiSteamFarm V5.5.2.3 (win-x64/12345678-1234-1234-1234-123456789012 | .NET 8.0.1; win-x64; Microsoft Windows 10)
2024-02-12 23:13:27|ArchiSteamFarm-12345|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
2024-02-12 23:13:27|ArchiSteamFarm-12345|INFO|ASF|InitPlugins() Initializing Plugins...
2024-02-12 23:13:27|ArchiSteamFarm-12345|INFO|ASF|InitPlugins() Loading CS2Interface V1.0.4.0...
2024-02-12 23:13:27|ArchiSteamFarm-12345|INFO|ASF|OnLoaded() Counter-Strike 2 Interface ASF Plugin by Citrinate
2024-02-12 23:13:27|ArchiSteamFarm-12345|INFO|ASF|InitPlugins() CS2Interface has been loaded successfully!
2024-02-12 23:13:27|ArchiSteamFarm-12345|INFO|ASF|InitPlugins() You've loaded one or multiple custom plugins into ASF. Since we're unable to offer support for modded setups, please contact the appropriate developers of the plugins that you decided to use in case of any issues.
2024-02-12 23:13:28|ArchiSteamFarm-12345|INFO|ASF|UpdateAndRestart() ASF will automatically check for new versions every 1 day.
2024-02-12 23:13:28|ArchiSteamFarm-12345|INFO|ASF|Update() Checking for new version...
2024-02-12 23:13:28|ArchiSteamFarm-12345|FATAL|ASF|OnUnhandledException() System.ArgumentException: The value cannot be an empty string. (Parameter 'message')
   at System.ArgumentException.ThrowNullOrEmptyException(String, String)
   at System.ArgumentException.ThrowIfNullOrEmpty(String , String )
   at ArchiSteamFarm.NLog.ArchiLogger.LogGenericError(String message, String previousMethodName)
   at CS2Interface.GameData.DoUpdate()
   at CS2Interface.GameData.<>c.<<-cctor>b__12_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2024-02-12 23:13:28|ArchiSteamFarm-12345|INFO|ASF|Update() Local version: 5.5.2.3 | Remote version: 5.5.2.3
2024-02-12 23:13:28|ArchiSteamFarm-12345|ERROR|ASF|Exit() Exiting with nonzero error code!
```

**Comment by Citrinate** [comment] 2024-02-12 23:25
I can confirm this is due to not using ASF-generic.  It's possible I might not be able to fix this as the error is coming from a dependency the plugin requires and not the plugin itself.

You could try this version, I don't expect this to fix the issue, but you should at least get a different error and it might not crash: https://github.com/Citrinate/CS2Interface/actions/runs/7879208384/artifacts/1239901635

**Comment by iBreakEverything** [comment] 2024-02-13 20:28
yes, i did get a different error and it seems it comes from ValveKeyValue.dll
```
2024-02-13 22:14:55|ArchiSteamFarm-1234|ERROR|ASF|DoUpdate() System.TypeLoadException
   at ValveKeyValue.Deserialization.KV1TextReader.ReadObject()
   at ValveKeyValue.KVSerializer.Deserialize(Stream stream, KVSerializerOptions options) in /home/runner/work/ValveKeyValue/ValveKeyValue/ValveKeyValue/ValveKeyValue/KVSerializer.cs:line 42
   at CS2Interface.GameDataResource.FetchKVResource(KVSerializerOptions options)
   at CS2Interface.GameDataItems.Update()
   at CS2Interface.GameData.DoUpdate()
```

**Comment by Citrinate** [comment] 2024-02-18 23:21
This issue should be fixed in the next release which will come in a few days.

You can test the current build with the fix here: https://github.com/Citrinate/CS2Interface/actions/runs/7952380989/artifacts/1255016677

**Closed** 2024-03-04 13:55 UTC
